name: Publish to Maven Central
on:
  push:
    branches: ['master']
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Will start a Maven Central upload with version $GITHUB_REF_NAME"
        if: ${{ github.ref_type == 'tag' }}

      - run: echo "Will start a Maven Central snapshot upload"
        if: ${{ github.ref_type != 'tag' }}

      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: oss.sonatype.org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set projection version to $GITHUB_REF_NAME
        run: mvn versions:set "-DnewVersion=$GITHUB_REF_NAME"
        if: ${{ github.ref_type == 'tag' }}

      - name: Publish package
        run: mvn --batch-mode clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
